### ISSUE TITLE
Russian <ru.cfg>

### ISSUE THREAD

**Issue by zer0Kerbal** [zer0Kerbal/KlockheedMartianLtd#15]
# Localization - ![Русский][RU] Russian (Русский) <ru.cfg>

## GitHub

* [x] assign
  * [x] zer0Kerbal
  * [x] Repo Localization Project
  * [x] Label: type: localization
  * [x] Label: help-wanted
  * [x] Milestone: Localization - Master

### GameData

* [x] add  Localization\[ru.cfg] 🗃️

### Translation

* [x] ![Русский][RU] Russian (Русский) <ru.cfg>

### Documentation

* [x] Update [readme.md] 🔢
* [x] Update [release.md] 🧾

### Wiki

* [x] Update docs/[localization.md]

## Update Social Media

* [x] GitHub (automated) (zer0Kerbal/zer0Kerbal)
* [x] CurseForge
* [x] Reddit
* [x] Twitter @zer0Kerbal
* [x] Forum
* [x] Patreon
* [x] SpaceDock
* [x] CKAN (automated)

[URL:lclztn]: https://github.com/zer0Kerbal/lclztn/blob/master/readme.md "Localization"
[URL:qs]: https://github.com/zer0Kerbal/lclztn/blob/master/quickstart.md "Quick Start"

[RU]: https://raw.githubusercontent.com/zer0Kerbal/zer0Kerbal/zed'K/Localization/img/Russian-flag-sm.png "Русский"

**Comment by evanisrael** [comment]
@zer0Kerbal done:)
PR link:
https://github.com/zer0Kerbal/KlockheedMartianLtd/pull/45

**Comment by zer0Kerbal** [comment]
@evanisrael 
> @zer0Kerbal done:) PR link: #45

wow. impressive. and most, well, moar. 😍🤗🤩

did you do this by hand or feed the files into Marvin, the robot?

Additional phrases have been added to en-us.cfg. would you mind adding them to the ru.cfg? (am releasing new version as we speak)

Will take me a week or two to release all these new translations. Am happy about these localizations!

**Comment by evanisrael** [comment]
@zer0Kerbal Done, new lines added to the commit in the same PR:)


> did you do this by hand or feed the files into Marvin, the robot?

90% of the text were translated by hand, another 10% are specific niche termins that I personally didn't know so required some googling and dictionary helping:)



> Will take me a week or two to release all these new translations. Am happy about these localizations!

Glad I could help! :smiling_face_with_three_hearts:
If you ever need any other help with translation, feel free to reach me^^

**Comment by zer0Kerbal** [comment]
> If you ever need any other help with translation, feel free to reach me^^

Thank you, I shall. Have added more existing Russian localization/translation issues in the Localization project (https://github.com/users/zer0Kerbal/projects/34) and more will pop up there as I continue to update and adopt.
