### ISSUE TITLE
Brazilian Portuguese (Português Brasil) <pt-br.cfg>

### ISSUE THREAD

**Issue by zer0Kerbal** [zer0Kerbal/KlockheedMartianLtd#9]
# Localization - ![Português Brasil][BR] Brazilian Portuguese (Português Brasil) <pt-br.cfg>

## GitHub

* [x] assign
  * [x] zer0Kerbal
  * [x] Repo Localization Project
  * [x] Label: localization
  * [x] Label: help-wanted
  * [x] Milestone: Localization - Master

### GameData

* [x] add  Localization\[pr-br.cfg] 🗃️

### Translation

* [x] ![Português Brasil][BR] Brazilian Portuguese (Português Brasil) <pt-br.cfg>

### Documentation

* [x] Update [readme.md] 🔢
* [x] Update [release.md] 🧾

### Wiki

* [x] Update docs/[localization.md]

## Update Social Media

* [x] GitHub (automated) (zer0Kerbal/zer0Kerbal)
* [x] CurseForge
* [x] Reddit
* [x] Twitter @zer0Kerbal
* [x] Forum
* [x] Patreon
* [x] SpaceDock
* [x] CKAN (automated)

[URL:lclztn]: https://github.com/zer0Kerbal/lclztn/blob/master/readme.md "Localization"
[URL:qs]: https://github.com/zer0Kerbal/lclztn/blob/master/quickstart.md "Quick Start"

[BR]: https://raw.githubusercontent.com/zer0Kerbal/zer0Kerbal/zed'K/Localization/img/Brazilian-flag-sm.png "Brazil"

**Comment by zer0Kerbal** [comment]
@lisias

**Comment by Lisias** [comment]
Hi! 

Pull request available: https://github.com/zer0Kerbal/KlockheedMartianLtd/pull/34

Cheers!

**Comment by zer0Kerbal** [comment]
> Hi!
> 
> Pull request available: #34
> 
> Cheers!

Thank you!
